spring:
  debug: true
  datasource:
    url: jdbc:postgresql://192.168.56.101:5432/payment_service
    username: postgres
    password: a_passwd234
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
        format_sql: true
        ddl-auto: update
  mvc:
    problemdetails:
      enabled: true
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    root: DEBUG
server:
  port : 8081
